
pipeline {
    agent any  // Runs on any available agent

    stages {
        stage('Clone GitHub Repository') {
            steps {
                // Clone the repository from GitHub
                git url: 'https://github.com/mhdnurfaizzy/seleniumFramewokDesign/', branch: 'main'
            }
        }
    }
}
